name: Akcje
on: 
  schedule:
    - cron: '36 13 * * 1'
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  test-Run:
    runs-on: windows-latest
    steps: 
       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
